name: Build and Deploy Unstable Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx

      - name: Build documentation
        run: |
          cd src/bonsai/docs
          make html

      - name: Deploy to GitHub Pages (Unstable)
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: IfcOpenShell/bonsaibim_org_docs_unstable
          publish_branch: main
          cname: docs-unstable.bonsaibim.org
          publish_dir: src/bonsai/docs/_build/html
